### ISSUE TITLE
Register User

### ISSUE THREAD

**Issue by camilaiperez** [mpeterson123/sweng894group8-mealplanner#2]
Priority: 5
Description: New user signs up for account given first name, last name, email, username, and initial password.
Pre-conditions:
User is on website homepage

Post-conditions:
User has an account and can log in

Success scenario:
User selects “register”.
User enters first name, last name, email, username, and password.
User clicks submit.
User goes to their email and clicks confirm email link that was sent to them.

Extensions:

Exceptions:

**Comment by Lsell1** [comment]
"User goes to their email and clicks confirm email link that was sent to them" will be moved to a later sprint
